dist: trusty
sudo: required

language: erlang
otp_release:
  - 20.0
  - 19.0
  - 18.0

script:
  - cat /var/log/mongodb/mongod.log
  - escript rebar3 eunit
  - escript rebar3 ct

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
  - echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
  - sudo apt-get update -q
  - sudo rm -rf /var/lib/mongodb
  - sudo apt-get install -y mongodb-org
  - sudo service mongod start
  - ./_download_rebar3.sh

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
